### ISSUE TITLE
Add link to associated blog post to readme? 

### ISSUE THREAD

**Issue by Patronics** [riktw/LitexTang9KExperiments#1]
To help anyone else that, like me, found this git repo without context when initially searching on github, could you add [a link to your blog post](https://justanotherelectronicsblog.com/?p=1263) that goes with this code to readme.md? Preferably also a bit of a short description overall, but the link to your blog post should be mostly sufficient.

**Comment by riktw** [comment]
Yeah, very good point. I'll do that right away!
